---
title: "ES_ARIMA"
author: "Victor Felix"
date: "2024-06-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library("tidyr")
library("MMWRweek")
library("data.table")
library("caret")
library("purrr")
library("dplyr")
library("tseries")
library("gtools")
library("forecast")
library("scoringutils")
library("covidHubUtils")
library("parallel")
library("future")#https://cran.r-project.org/web/packages/future/vignettes/future-4-issues.html
library("listenv")
library("epitools")
library("ggplot2")
library("sf")
```

in the document. You can embed an R code chunk like this:

```{r cars}
load("ARIMA_MODELS.Rdata")
load("TEMPERATURE_MODELS.Rdata")
```

SAVE AS FUNCTIONS LATER

```{r}

# Define the function
calculate_mean_abs_error <- function(state_list) {
  # Get the number of states in the list
  num_states <- length(state_list)
  
  # Initialize vectors to store state names and mean values
  state_names <- vector("character", length = num_states)
  mean_values <- vector("numeric", length = num_states)
  
  # Iterate through the states
  for (state in 1:num_states) {
    # Get the name of the state
    state_name <- names(state_list)[state]
    
    # Get the mean WIS value for the state
    mean_wis <- mean(state_list[[state]]$abs_error)
    
    # Store the state name and mean value in the vectors
    state_names[state] <- state_name
    mean_values[state] <- mean_wis
  }
  
  # Create a data frame
  results_df <- data.frame(State = state_names, Mean_WIS = mean_values)
  
  # Return the data frame
  return(results_df)
}

# Define the function
calculate_mean_wis <- function(state_list) {
  # Get the number of states in the list
  num_states <- length(state_list)
  
  # Initialize vectors to store state names and mean values
  state_names <- vector("character", length = num_states)
  mean_values <- vector("numeric", length = num_states)
  
  # Iterate through the states
  for (state in 1:num_states) {
    # Get the name of the state
    state_name <- names(state_list)[state]
    
    # Get the mean WIS value for the state
    mean_wis <- mean(state_list[[state]]$WIS)
    
    # Store the state name and mean value in the vectors
    state_names[state] <- state_name
    mean_values[state] <- mean_wis
  }
  
  # Create a data frame
  results_df <- data.frame(State = state_names, Mean_WIS = mean_values)
  
  # Return the data frame
  return(results_df)
}

```

WEEK1

```{r}
W1<-NULL

# Example usage with AUTO_ARIMA_WEEK1_list
AUTO_W1 <- calculate_mean_wis(AUTO_ARIMA_WEEK1_list)
ES27_W1 <- calculate_mean_wis(ES27_ARIMA_WEEK1_list)
ES64_W1 <- calculate_mean_wis(ES64_ARIMA_WEEK1_list)

# Print the results
# Merge the results by state names
W1 <- merge(AUTO_W1, ES27_W1, by = "State")
W1 <- merge(W1, ES64_W1, by = "State")

# Rename columns for clarity
colnames(W1)[2] <- "AUTO_W1"
colnames(W1)[3] <- "ES27_W1"
colnames(W1)[4] <- "ES64_W1"

# Identify the best result for each state
W1$Best_Result <- apply(W1[,2:4], 1, function(x) {
  which.min(x)
})

# Print the merged results
print(W1)

```

WEEK 2

```{r}
W2<-NULL

# Example usage with AUTO_ARIMA_WEEK1_list
AUTO_W2 <- calculate_mean_wis(AUTO_ARIMA_WEEK2_list)
ES27_W2 <- calculate_mean_wis(ES27_ARIMA_WEEK2_list)
ES64_W2 <- calculate_mean_wis(ES64_ARIMA_WEEK2_list)

# Print the results
# Merge the results by state names
W2 <- merge(AUTO_W2, ES27_W2, by = "State")
W2 <- merge(W2, ES64_W2, by = "State")

# Rename columns for clarity
colnames(W2)[2] <- "AUTO_W2"
colnames(W2)[3] <- "ES27_W2"
colnames(W2)[4] <- "ES64_W2"

# Identify the best result for each state
W2$Best_Result <- apply(W2[,2:4], 1, function(x) {
  which.min(x)
})

# Print the merged results
print(W2)

```

WEEK 3

```{r}
W3<-NULL

# Example usage with AUTO_ARIMA_WEEK1_list
AUTO_W3 <- calculate_mean_wis(AUTO_ARIMA_WEEK3_list)
ES27_W3 <- calculate_mean_wis(ES27_ARIMA_WEEK3_list)
ES64_W3 <- calculate_mean_wis(ES64_ARIMA_WEEK3_list)

# Print the results
# Merge the results by state names
W3 <- merge(AUTO_W3, ES27_W3, by = "State")
W3 <- merge(W3, ES64_W3, by = "State")

# Rename columns for clarity
colnames(W3)[2] <- "AUTO_W3"
colnames(W3)[3] <- "ES27_W3"
colnames(W3)[4] <- "ES64_W3"

# Identify the best result for each state
W3$Best_Result <- apply(W3[,2:4], 1, function(x) {
  which.min(x)
})

# Print the merged results
print(W3)

```

WEEK 4

```{r}
W4<-NULL

# Example usage with AUTO_ARIMA_WEEK1_list
AUTO_W4 <- calculate_mean_wis(AUTO_ARIMA_WEEK4_list)
ES27_W4 <- calculate_mean_wis(ES27_ARIMA_WEEK4_list)
ES64_W4 <- calculate_mean_wis(ES64_ARIMA_WEEK4_list)

# Print the results
# Merge the results by state names
W4 <- merge(AUTO_W4, ES27_W4, by = "State")
W4 <- merge(W4, ES64_W4, by = "State")

# Rename columns for clarity
colnames(W4)[2] <- "AUTO_W4"
colnames(W4)[3] <- "ES27_W4"
colnames(W4)[4] <- "ES64_W4"

# Identify the best result for each state
W4$Best_Result <- apply(W4[,2:4], 1, function(x) {
  which.min(x)
})

# Print the merged results
print(W4)

```


```{r}

# --------- Previous MODELS ------------- #
ggplot(W1,aes(x=Best_Result)) + geom_bar()+
  labs(title = "Week 1",
       x = "BEST MODELS", y="Number of Models") 

# --------- Previous MODELS ------------- #
ggplot(W2,aes(x=Best_Result)) + geom_bar()+
  labs(title = "Week 2",
       x = "BEST MODELS", y="Number of Models") 

# --------- Previous MODELS ------------- #
ggplot(W3,aes(x=Best_Result)) + geom_bar()+
  labs(title = "Week 3",
       x = "BEST MODELS", y="Number of Models") 

# --------- Previous MODELS ------------- #
ggplot(W4,aes(x=Best_Result)) + geom_bar()+
  labs(title = "Week 4",
       x = "BEST MODELS", y="Number of Models") 


```


```{r pressure, echo=FALSE}


#######################################################
# MAPPING THE MEAN PERFORMANCE OF THE ES64, ES27      #
# AND AUTO ARIMA MODELS FOR THE 50 STATES OF THE U.S. #
# BASED ON THE SUMMARY RESULTS OF THE CURRENT MODELS. #
#######################################################

states <- read_sf("cb_2018_us_state_500k/cb_2018_us_state_500k.shp")

#df <- subset(current_models, select = c(Name,MEAN_WIS,WEEK_AHEAD,BEST_WIS))

W1_<-setNames(W1, c("NAME","MEAN_WIS","ES27","ES64","BEST_WIS"))

##########################
# MEAN WIS 1 week ahead #
########################

target <- c(1)
week1<-W1_
map_week1<-left_join(states, week1, by=join_by("NAME"))%>%
  drop_na()

ES_1WEEK<- ggplot(map_week1, fill ="lightgrey") +  theme_light()  + geom_sf(aes(fill=log1p(MEAN_WIS))) +  scale_fill_distiller("WIS", palette="Spectral") +  ggtitle("MEAN LINEAR MODELS PERFORMANCE - 1 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_1WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  

```



```{r pressure, echo=FALSE}
#######################################################
# MAPPING THE BEST PERFORMANCE OF THE ES64, ES27      #
# AND AUTO ARIMA MODELS FOR THE 50 STATES OF THE U.S. #
# BASED ON THE SUMMARY RESULTS OF THE CURRENT MODELS. #
#######################################################

target <- c(1)
week1<-W1

##########################
# MEAN WIS 1 week ahead #
########################

ES_1WEEK<- ggplot(map_week1, fill ="lightgrey") +  theme_minimal()  + geom_sf(aes(fill=BEST_WIS)) +  scale_fill_distiller("NAME", palette="RdYlBu") +  ggtitle("BEST LINEAR MODEL - 1 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_1WEEK + coord_sf(xlim = x_limits, ylim = y_limits) 

```

```{r pressure, echo=FALSE}
##########################
# MEAN WIS 2 week ahead #
########################
target <- c(2)
week2<-df %>%
  filter(N_WEEK_AHEAD == target)

map_week2<-left_join(states, week2,by="NAME")%>%
  drop_na()

ES_2WEEK<- ggplot(map_week2, fill ="lightgrey") +  theme_light()  + geom_sf(aes(fill=MEAN_WIS)) +  scale_fill_distiller("WIS", palette="Spectral") +  ggtitle("MEAN LINEAR MODELS PERFORMANCE - 2 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_2WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  

##########################
# MEAN WIS 3 week ahead #
########################

target <- c(3)
week3<-df %>%
  filter(N_WEEK_AHEAD == target)

map_week3<-left_join(states, week3, by="NAME")%>%
  drop_na()

ES_3WEEK<- ggplot(map_week3, fill ="lightgrey") +  theme_light()  + geom_sf(aes(fill=log(MEAN_WIS))) +  scale_fill_distiller("WIS", palette="Spectral") +  ggtitle("MEAN LINEAR MODELS PERFORMANCE - 3 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_3WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  

##########################
# MEAN WIS 4 week ahead #
########################

target <- c(4)
week4<-df %>%
  filter(N_WEEK_AHEAD == target)

map_week4<-left_join(states, week4,by="NAME")%>%
  drop_na()

ES_4WEEK<- ggplot(map_week4, fill ="lightgrey") +  theme_light()  + geom_sf(aes(fill=log(MEAN_WIS))) +  scale_fill_distiller("WIS", palette="Spectral") +  ggtitle("MEAN LINEAR MODELS PERFORMANCE - 4 WEEK AHEAD") 

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_4WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  
```
