---
title: "maps_and_graphs"
author: "Victor Felix"
date: "2024-06-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

!!!!!!!!!!!!!!!!!!!!
LOADING THE PACKAGES
!!!!!!!!!!!!!!!!!!!!
```{r}
library("tidyr")
library("MMWRweek")
library("data.table")
library("caret")
library("purrr")
library("dplyr")
library("tseries")
library("gtools")
library("forecast")
library("scoringutils")
library("covidHubUtils")
library("parallel")
library("future")#
library("listenv")
library("epitools")
```


```{r cars}
current_models <- read.csv('ES_RESULTS.csv')

ggplot(current_models, aes(x = AUTO)) +
  geom_histogram(binwidth = 10, fill = "blue", color = "black") +
  geom_vline(data = current_models, aes(xintercept = AUTO), color = "red", linetype = "dashed") +
  facet_wrap(~ WEEK_AHEAD, nrow = 2) +
  labs(title = "AUTO ARIMA Weighted Interval Score for 50 US states",
       x = "Weighted Interval Score",
       y = "Frequency") +
  annotate("text", x = current_models$Value, y = 2, label = current_models$Value, color = "red") +
  theme_minimal()

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}


#######################################################
# MAPPING THE MEAN PERFORMANCE OF THE ES64, ES27      #
# AND AUTO ARIMA MODELS FOR THE 50 STATES OF THE U.S. #
# BASED ON THE SUMMARY RESULTS OF THE CURRENT MODELS. #
#######################################################

states <- read_sf("cb_2018_us_state_500k/cb_2018_us_state_500k.shp")

df <- subset(current_models, select = c(Name,MEAN_WIS,WEEK_AHEAD,BEST_WIS))

df<-setNames(df, c("NAME","MEAN_WIS","N_WEEK_AHEAD","BEST_WIS"))

##########################
# MEAN WIS 1 week ahead #
########################

target <- c(1)
week1<-df %>%
  filter(N_WEEK_AHEAD == target)

map_week1<-left_join(states, week1, by=join_by("NAME"))%>%
  drop_na()

ES_1WEEK<- ggplot(map_week1, fill ="lightgrey") +  theme_light()  + geom_sf(aes(fill=log(MEAN_WIS))) +  scale_fill_distiller("WIS", palette="Spectral") +  ggtitle("MEAN LINEAR MODELS PERFORMANCE - 1 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_1WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  

##########################
# MEAN WIS 2 week ahead #
########################

target <- c(2)
week2<-df %>%
  filter(N_WEEK_AHEAD == target)

map_week2<-left_join(states, week2,by="NAME")%>%
  drop_na()

ES_2WEEK<- ggplot(map_week2, fill ="lightgrey") +  theme_light()  + geom_sf(aes(fill=log(MEAN_WIS))) +  scale_fill_distiller("WIS", palette="Spectral") +  ggtitle("MEAN LINEAR MODELS PERFORMANCE - 2 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_2WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  

##########################
# MEAN WIS 3 week ahead #
########################

target <- c(3)
week3<-df %>%
  filter(N_WEEK_AHEAD == target)

map_week3<-left_join(states, week3, by="NAME")%>%
  drop_na()

ES_3WEEK<- ggplot(map_week3, fill ="lightgrey") +  theme_light()  + geom_sf(aes(fill=log(MEAN_WIS))) +  scale_fill_distiller("WIS", palette="Spectral") +  ggtitle("MEAN LINEAR MODELS PERFORMANCE - 3 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_3WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  

##########################
# MEAN WIS 4 week ahead #
########################

target <- c(4)
week4<-df %>%
  filter(N_WEEK_AHEAD == target)

map_week4<-left_join(states, week4,by="NAME")%>%
  drop_na()

ES_4WEEK<- ggplot(map_week4, fill ="lightgrey") +  theme_light()  + geom_sf(aes(fill=log(MEAN_WIS))) +  scale_fill_distiller("WIS", palette="Spectral") +  ggtitle("MEAN LINEAR MODELS PERFORMANCE - 4 WEEK AHEAD") 

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_4WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
#######################################################
# MAPPING THE BEST PERFORMANCE OF THE ES64, ES27      #
# AND AUTO ARIMA MODELS FOR THE 50 STATES OF THE U.S. #
# BASED ON THE SUMMARY RESULTS OF THE CURRENT MODELS. #
#######################################################

target <- c(1)
week1<-df %>%
  filter(N_WEEK_AHEAD == target)

##########################
# MEAN WIS 1 week ahead #
########################

ES_1WEEK<- ggplot(map_week1, fill ="lightgrey") +  theme_minimal()  + geom_sf(aes(fill=BEST_WIS)) +  scale_color_fermenter("NAME", palette="RdYlBu") +  ggtitle("BEST LINEAR MODEL - 1 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_1WEEK + coord_sf(xlim = x_limits, ylim = y_limits) 

##########################
# MEAN WIS 2 week ahead #
########################

target <- c(2)
week2<-df %>%
  filter(N_WEEK_AHEAD == target)

ES_2WEEK<- ggplot(map_week2, fill ="lightgrey") +  theme_minimal()  + geom_sf(aes(fill=BEST_WIS)) +  scale_color_fermenter("NAME", palette="RdYlBu") +  ggtitle("BEST LINEAR MODEL - 2 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_2WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  

##########################
# MEAN WIS 3 week ahead #
########################

target <- c(3)
week3<-df %>%
  filter(N_WEEK_AHEAD == target)

ES_3WEEK<- ggplot(map_week3, fill ="lightgrey") +  theme_minimal()  + geom_sf(aes(fill=BEST_WIS)) +  scale_color_fermenter("NAME", palette="RdYlBu") +  ggtitle("BEST LINEAR MODEL - 3 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_3WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  

##########################
# MEAN WIS 4 week ahead #
########################

target <- c(4)
week4<-df %>%
  filter(N_WEEK_AHEAD == target)

ES_4WEEK<- ggplot(map_week4, fill ="lightgrey") +  theme_minimal()  + geom_sf(aes(fill=BEST_WIS)) +  scale_color_fermenter("NAME", palette="RdYlBu") +  ggtitle("BEST LINEAR MODEL - 4 WEEK AHEAD")

x_limits <- c(-180, -70)  # Set the desired longitude range
y_limits <- c(20, 70)    # Set the desired latitude range

ES_4WEEK + coord_sf(xlim = x_limits, ylim = y_limits)  


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
